import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr'
import { Container, Grid } from '@mui/material'
import WeatherCard, { WeatherCardProps } from '../components/WeatherCard'
import HeaterCard from '../components/HeaterCard'
import GrassIcon from '@mui/icons-material/Grass'
import Brightness7Icon from '@mui/icons-material/Brightness7'
import WaterIcon from '@mui/icons-material/Water'
import ReportGmailerrorredOutlinedIcon from '@mui/icons-material/ReportGmailerrorredOutlined'
import HourglassBottomOutlinedIcon from '@mui/icons-material/HourglassBottomOutlined'
import Loading from '../components/Loading'

type IgorsData = {
  heater: Boolean | null
  above: Number
  below: Number
  humidity: Number
}

async function fetcher<JSON = any>(
  input: RequestInfo,
  init?: RequestInit
): Promise<JSON> {
  const res = await fetch(input, init)
  return res.json()
}

const Home: NextPage = () => {
  const { data: igorsData, error } = useSWR<IgorsData>('/api/igors', fetcher)
  if (error) return <Loading icon={ReportGmailerrorredOutlinedIcon} />
  if (!igorsData) return <Loading icon={HourglassBottomOutlinedIcon} />

  const values: WeatherCardProps[] = [
    { value: igorsData.above, type: 'temperature', icon: Brightness7Icon },
    { value: igorsData.below, type: 'temperature', icon: GrassIcon },
    { value: igorsData.humidity, type: 'humidity', icon: WaterIcon },
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid
          container
          style={{ minHeight: '100vh' }}
          justifyContent="center"
          alignItems="center"
        >
          <Container maxWidth="xl">
            <Grid
              container
              spacing={2}
              justifyContent="center"
              alignItems="center"
            >
              {values.map((v, idx) => (
                <Grid
                  key={idx}
                  item
                  container
                  xs={12}
                  xl={12 / (values.length + 1)}
                  justifyContent="center"
                  alignItems="center"
                >
                  <WeatherCard value={v.value} type={v.type} icon={v.icon} />
                </Grid>
              ))}
              <Grid
                item
                container
                xs={12}
                xl={3}
                justifyContent="center"
                alignItems="center"
              >
                <HeaterCard value={igorsData.heater} />
              </Grid>
            </Grid>
          </Container>
        </Grid>
      </main>
    </>
  )
}

export default Home
